apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-front-deploy
  labels:
    app: video-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: video-front
  template:
    metadata:
      labels:
        app: video-front
    spec:
      containers:
      - name: video-front
        image: gcr.io/archidistri/frontconverter@sha256:bb9b6ea0538df6581d93075144a682878474e989248fc5156c212877eb00f673
        ports:
        - containerPort: 42308
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: video-front-service
spec:
  selector:
    app: video-front
  ports:
    - port: 42308
      targetPort: 42308
      nodePort: 30008
  type: LoadBalancer
