@startuml
package "Google CLoud" {
    folder "Kubernetes" {
        node "video-front" {
            [java 8]
            [video-dispatcher]
        }
    }
    folder "Kubernetes" {
        node "video-back" {
            [python]
            [video converter]
        }
    }
}
package "Android APP" {
    node "Android" {
        [vc-client]
    }
}
package "Azure Cloud" {
    [azure file storage]
    database "mongodb"
}


[vc-client] -> [video-dispatcher]
[azure file storage] -> [video converter]
[video-dispatcher] -> "mongodb"
@enduml