@startuml
top to bottom direction
skinparam packageStyle cloud
package "Google CLoud" {
    folder "Kubernetes" {
        node "video-front" {
            [java 8]
            [video-dispatcher]
        }
    }
    folder "Kubernetes" {
        node "video-back" {
            [python]
            [video converter]
        }
    }
    folder "pubsub" {
        queue "pubsub channel" as ps
    }
}
together {
skinparam packageStyle package
package "Android APP" {
    node "Android" {
        [vc-client]
    }
}
skinparam packageStyle cloud
package "Azure Cloud" {
    [azure file storage]
    database "mongodb" as mongo
}
}


[vc-client] - [video-dispatcher] : https && websocket
[azure file storage] - [video converter]
[video converter] - mongo
[video-dispatcher] - mongo
[video converter] - [video-dispatcher] : websocket
[video-dispatcher] - [azure file storage]
ps - [video converter]
ps - [video-dispatcher]
@enduml