server :
  port : 42308
  ssl:
    enabled: true
    key-store: "ssl/keystore.pkcs12"
    key-store-password: ezip
    keyStoreType: PKCS12

spring :
  data :
    mongodb :
      host : 192.168.0.193
      port : 27017
      database : ezipflix
  cloud :
    gcp:
      project-id: archidistri
      credentials:
        location : file:ArchiDistri.json

