server :
  port : 42308
  ssl:
    enabled: true
    key-store: "ssl/keystore.pkcs12"
    key-store-password: ezip
    keyStoreType: PKCS12

spring :
  data :
    mongodb :
      uri : mongodb+srv://archi:archi@archi-mogo-kqt4l.azure.mongodb.net/ezipflix?retryWrites=true&w=majority
      database : ezipflix
  cloud :
    gcp:
      project-id: archidistri
      credentials:
        location : file:ArchiDistri.json

